package com.example.fusedlocation

const val CUSTOM_INTENT_ACTIVITY_ACTION = "CUSTOM_INTENT_ACTIVITY_ACTION"
const val CUSTOM_REQUEST_CODE_ACTIVITY_UPDATE = 1000
const val CUSTOM_REQUEST_CODE_ACTIVITY_TRANSITION = 1001
